<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>微软图标.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="微软图标.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SunnyUI" Version="3.9.3" />
    <PackageReference Include="System.Text.Json" Version="10.0.5" />
    <PackageReference Include="TouchSocket" Version="4.1.12" />
    <PackageReference Include="TouchSocket.Core" Version="4.1.12" />
    <PackageReference Include="TouchSocket.Http" Version="4.1.12" />
    <PackageReference Include="TouchSocket.JsonRpc" Version="4.1.12" />
    <PackageReference Include="TouchSocket.Rpc" Version="4.1.12" />
  </ItemGroup>

</Project>